name: Build check

on:
  pull_request:
    types: [opened, synchronize, reopend]
    branches: [main]

jobs:
  build:
    name: go build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["linux", "windows"]
        arch: ["amd64"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - run: go mod tidy && go mod vendor

      - run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build .
